name: found
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - alabaster==0.7.16
      - altgraph==0.17.3
      - annotated-types==0.7.0
      - ansi2html==1.9.2
      - antropy==0.1.4
      - appdirs==1.4.4
      - asttokens==3.0.0
      - attrs==22.1.0
      - auto-py-to-exe==2.23.1
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bib-lookup==0.0.29
      - bidict==0.23.1
      - biobss==0.1.1
      - biosppy==2.2.3
      - boltons==21.0.0
      - boto3==1.38.43
      - botocore==1.38.43
      - bottle==0.12.23
      - bottle-websocket==0.2.9
      - certifi==2022.9.24
      - cffi==1.15.1
      - chardet==5.0.0
      - charset-normalizer==2.1.1
      - click==8.2.1
      - colorama==0.4.5
      - comm==0.2.2
      - contourpy==1.0.5
      - css-html-js-minify==2.5.5
      - cvxopt==1.3.0
      - cycler==0.11.0
      - cython==3.1.2
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.14
      - decorator==5.1.1
      - deprecate-kwargs==0.1.0
      - deprecated==1.2.18
      - docutils==0.18.1
      - dotmap==1.3.30
      - dotteddict==2016.3.11
      - easydict==1.13
      - eel==0.14.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - face==20.1.1
      - fastdtw==0.3.4
      - feedparser==6.0.11
      - filelock==3.18.0
      - flask==2.1.3
      - flask-cors==3.0.10
      - fonttools==4.37.1
      - fsspec==2025.5.0
      - future==0.18.2
      - gatspy==0.3
      - gevent==21.12.0
      - gevent-websocket==0.10.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glom==22.1.0
      - greenlet==1.1.3
      - grpcio==1.73.1
      - h5py==3.14.0
      - heartpy==1.2.7
      - huggingface-hub==0.31.4
      - idna==3.4
      - imagesize==1.4.1
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipython==8.37.0
      - ipython-genutils==0.2.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-dash==0.4.2
      - kiwisolver==1.4.4
      - llvmlite==0.43.0
      - lxml==5.4.0
      - markdown==3.8.2
      - markupsafe==2.1.1
      - matplotlib==3.6.1
      - matplotlib-inline==0.1.7
      - mne==1.5.0
      - mock==5.2.0
      - mpldatacursor==0.7.1
      - mpmath==1.3.0
      - nbformat==4.2.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - neurokit2==0.1.7
      - numba==0.60.0
      - numpy==1.23.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.5.3
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.10.18
      - packaging==21.3
      - pandas==1.4.4
      - parallel-map==0.2.1
      - parso==0.8.4
      - patsy==0.5.3
      - peakutils==1.3.5
      - pefile==2022.5.30
      - pexpect==4.9.0
      - pillow==9.2.0
      - pip==21.3.1
      - platformdirs==4.3.8
      - plotly==5.11.0
      - plotly-resampler==0.8.2
      - pooch==1.6.0
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-ecg-detectors==1.3.2
      - pyarrow==20.0.0
      - pycparser==2.21
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyedflib==0.1.40
      - pygments==2.19.2
      - pyinstaller==5.5
      - pyinstaller-hooks-contrib==2022.10
      - pyparsing==3.0.9
      - pyppg==1.0.41
      - python-dateutil==2.8.2
      - python-slugify==8.0.4
      - pytorch-metric-learning==2.8.1
      - pytorch-ranger==0.1.1
      - pytz==2022.4
      - pywavelets==1.4.1
      - pywin32-ctypes==0.2.0
      - pyyaml==6.0
      - pyzmq==27.0.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.28.1
      - retrying==1.4.0
      - rpds-py==0.25.1
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scikit-learn==1.1.3
      - scipy==1.9.1
      - sentry-sdk==2.33.2
      - setuptools==60.2.0
      - sgmllib3k==1.0.0
      - shortuuid==1.0.13
      - six==1.16.0
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soundfile==0.11.0
      - soupsieve==2.7
      - sphinx==7.3.7
      - sphinx-material==0.0.35
      - sphinx-rtd-theme==1.3.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - statsmodels==0.13.2
      - stochastic==0.7.0
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - text-unidecode==1.3
      - threadpoolctl==3.1.0
      - timm==1.0.15
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.3.1+cu121
      - torch-ecg==0.0.31
      - torch-optimizer==0.3.0
      - torchaudio==2.3.1+cu121
      - torchsummary==1.5.1
      - torchvision==0.18.1+cu121
      - tornado==6.5.1
      - tqdm==4.64.1
      - trace-updater==0.0.9.1
      - traitlets==5.14.3
      - transformers==4.52.1
      - triton==2.3.1
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unidecode==1.4.0
      - urllib3==1.26.12
      - vitaldb==1.5.4
      - wandb==0.21.0
      - wcwidth==0.2.13
      - werkzeug==2.1.2
      - wfdb==3.4.0
      - wheel==0.37.1
      - whichcraft==0.6.1
      - wrapt==1.17.2
      - xmltodict==0.14.2
      - zipp==3.23.0
      - zope-event==4.5.0
      - zope-interface==5.4.0
prefix: /home/yangyizhang1/anaconda3/envs/found
